### ISSUE TITLE
作者你好，请问显卡渲染问题Extension GL_ARB_bindless_texture is not available解决了吗

### ISSUE THREAD

**Issue by rongjv** [Time-Coder/Glass-Engine#3]
如题

**Comment by Time-Coder** [comment]
在阴影渲染和动态环境映射的实现中使用了无绑定纹理(bindless texture)，如果显卡不支持该扩展，阴影和动态环境映射将不生效，不过其他渲染效果正常。比较老的 intel 和 amd 显卡可能不支持 bindless texture 扩展，如果你的电脑含有高性能显卡，请将 python.exe 程序切换为使用该显卡。如果你的确需要在不支持 GL_ARB_bindless_texture 的显卡上启用阴影和动态环境映射，请告诉我，我将解决该问题。

**Comment by rongjv** [comment]
> 在阴影渲染和动态环境映射的实现中使用了无绑定纹理(bindless texture)，如果显卡不支持该扩展，阴影和动态环境映射将不生效，不过其他渲染效果正常。比较老的 intel 和 amd 显卡可能不支持 bindless texture 扩展，如果你的电脑含有高性能显卡，请将 python.exe 程序切换为使用该显卡。如果你的确需要在不支持 GL_ARB_bindless_texture 的显卡上启用阴影和动态环境映射，请告诉我，我将解决该问题。

发生的错误：
    camera.screen.show()
OpenGL.error.GLError: GLError(
	err = 1285,
	description = b'\xc4\xda\xb4\xe6\xb2\xbb\xd7\xe3',
	baseOperation = glGetProgramResourceIndex,
	pyArgs = (
		1,
		GL_SHADER_STORAGE_BLOCK,
		b'PointLights',
	),
	cArgs = (
		1,
		GL_SHADER_STORAGE_BLOCK,
		b'PointLights',
	),
	cArguments = (
		1,
		GL_SHADER_STORAGE_BLOCK,
		b'PointLights',
	),
	result = 1
)

**Comment by Time-Coder** [comment]
临时版本 0.1.52 已发布，应该解决了该问题，请尝试，有任何问题请回复，也可直接联系邮箱 binghui.wang@foxmail.com

**Comment by rongjv** [comment]
> 临时版本 0.1.52 已发布，应该解决了该问题，请尝试，有任何问题请回复，也可直接联系邮箱 [binghui.wang@foxmail.com](mailto:binghui.wang@foxmail.com)

我更新试了下，还是报错：
发生异常: OSError
exception: access violation reading 0x0000000000000000
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

  File "E:\100proworld2021\Python2022\AnyCAD-3DUI\glass3D.py", line 30, in <module>
    camera.screen.show()
OSError: exception: access violation reading 0x0000000000000000

**Comment by Time-Coder** [comment]
给我说一下你的显卡型号

**Comment by rongjv** [comment]
> 给我说一下你的显卡型号

![屏幕截图 2024-03-01 115143](https://github.com/Time-Coder/Glass-Engine/assets/60056273/f3eef2bc-8a40-4eb6-b780-370a828446e5)

**Comment by Time-Coder** [comment]
用 Intel(R) HD Graphics 5500 估计是没戏了，可以把 python 程序切换成使用 NVIDIA GeForce 940M，方法为打开NVIDIA控制面板，找见应用程序设置，在其中将 python.exe 设置为使用高性能显卡，然后再运行程序。

**Comment by Time-Coder** [comment]
如果还有问题，请先测试以下最简程序：

```python
from glass_engine import *

scene = Scene()
scene.background.color = glm.vec3(1, 0, 0)
camera = Camera()
scene.add(camera)
camera.screen.show()
```

此时期望出现全红屏幕

**Comment by rongjv** [comment]
> 如果还有问题，请先测试以下最简程序：
> 
> ```python
> from glass_engine import *
> 
> scene = Scene()
> scene.background.color = glm.vec3(1, 0, 0)
> camera = Camera()
> scene.add(camera)
> camera.screen.show()
> ```
> 
> 此时期望出现全红屏幕

我试了下，不进行修改的情况，运行这个最简单程序没问题，修改了Nvdia设置后，在运行之前的程序，也没问题了，但出现了一个警告：
E:/Program Files/Python312/Lib/site-packages/glass_engine/glsl/Pipelines/forward_rendering/forward_rendering.fs:1: warning: C7050: "view_pos.y" might be used before being initialized
  warnings.warn(warning_message, category=LinkWarning)
done
目前来看，是可以了，谢谢

**Comment by Time-Coder** [comment]
这个 warning 是个隐患，请在所有 import 之后加上 ``GlassConfig.debug = True``，然后再运行程序，我想看一下警告真实的行号。

**Comment by rongjv** [comment]
> 这个 warning 是个隐患，请在所有 import 之后加上 `GlassConfig.debug = True`，然后再运行程序，我想看一下警告真实的行号。

但这个只出现了一次，后面就没出现了

**Comment by Time-Coder** [comment]
> > 这个 warning 是个隐患，请在所有 import 之后加上 `GlassConfig.debug = True`，然后再运行程序，我想看一下警告真实的行号。
> 
> 但这个只出现了一次，后面就没出现了
那就在加一句：``GlassConfig.recompile = True``

**Comment by rongjv** [comment]
> GlassConfig.recompile = True

E:/Program Files/Python312/Lib/site-packages/glass_engine/glsl/Pipelines/forward_rendering/forward_rendering.fs:26: 
warning: C7050: "view_pos.y" might be used before being initialized
  warnings.warn(warning_message, category=LinkWarning)
done

**Comment by Time-Coder** [comment]
好的，我知道了，这是一个潜在bug，会影响半透明物体的渲染，下一版会将其修复。

非常感谢您使用 Glass-Engine，有任何其他问题欢迎提 issue，有任何使用上的问题也欢迎直接联系我的邮箱。

**Comment by rongjv** [comment]
> 好的，我知道了，这是一个潜在bug，会影响半透明物体的渲染，下一版会将其修复。
> 
> 非常感谢您使用 Glass-Engine，有任何其他问题欢迎提 issue，有任何使用上的问题也欢迎直接联系我的邮箱。

使用动态纹理时的报错，是因为显卡不行导致的吗？
发生异常: CompileError

E:/Program Files/Python312/Lib/site-packages/glass/glsl/shadertoy_template.fs:18: error: File ""E:/100proworld2021/Python2022/AnyCAD-3DUI/GLSLfile/zsq.glsl"" not exists.
  File "E:\100proworld2021\Python2022\AnyCAD-3DUI\glass3D.py", line 295, in zhuoseqi_func
    box.material.emission_map = "AnyCAD-3DUI\\GLSLfile\\zsq.glsl"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\100proworld2021\Python2022\AnyCAD-3DUI\glass3D.py", line 306, in <module>
    zhuoseqi_func()
glass.GPUProgram.CompileError: 
E:/Program Files/Python312/Lib/site-packages/glass/glsl/shadertoy_template.fs:18: error: File ""E:/100proworld2021/Python2022/AnyCAD-3DUI/GLSLfile/zsq.glsl"" not exists.
这个报错说文件不存在，但这个文件是存在的，内容是按照你说的，从shadertoy网站复制的一个动态纹理，然后复制保存到本地一个文件，格式为glsl，但是按照你给的动态纹理示例程序运行后出现了上面的错误

**Comment by Time-Coder** [comment]
动态纹理问题移动到新bug #5，周日(2024年3月3日)将发布新版解决该问题。

如果您喜欢 Glass-Engine，可以考虑在文档介绍页打赏，您的支持将成为开源创作的巨大动力。

**Comment by Time-Coder** [comment]
> > 好的，我知道了，这是一个潜在bug，会影响半透明物体的渲染，下一版会将其修复。
> > 非常感谢您使用 Glass-Engine，有任何其他问题欢迎提 issue，有任何使用上的问题也欢迎直接联系我的邮箱。
> 
> 使用动态纹理时的报错，是因为显卡不行导致的吗？ 发生异常: CompileError
> 
> E:/Program Files/Python312/Lib/site-packages/glass/glsl/shadertoy_template.fs:18: error: File ""E:/100proworld2021/Python2022/AnyCAD-3DUI/GLSLfile/zsq.glsl"" not exists. File "E:\100proworld2021\Python2022\AnyCAD-3DUI\glass3D.py", line 295, in zhuoseqi_func box.material.emission_map = "AnyCAD-3DUI\GLSLfile\zsq.glsl" ^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\100proworld2021\Python2022\AnyCAD-3DUI\glass3D.py", line 306, in zhuoseqi_func() glass.GPUProgram.CompileError: E:/Program Files/Python312/Lib/site-packages/glass/glsl/shadertoy_template.fs:18: error: File ""E:/100proworld2021/Python2022/AnyCAD-3DUI/GLSLfile/zsq.glsl"" not exists. 这个报错说文件不存在，但这个文件是存在的，内容是按照你说的，从shadertoy网站复制的一个动态纹理，然后复制保存到本地一个文件，格式为glsl，但是按照你给的动态纹理示例程序运行后出现了上面的错误

[v0.1.54](https://github.com/Time-Coder/Glass-Engine/releases/tag/v0.1.54) fix this bug
