### ISSUE TITLE
如果不在main中渲染会无法运行

### ISSUE THREAD

**Issue by Hello2015** [Time-Coder/Glass-Engine#9]
glass_engine\Screens\QtScreen.py", line 302, in paintGL
    should_update_scene = scene.generate_meshes()
AttributeError: 'method-wrapper' object has no attribute 'generate_meshes'

我这边是另外写了一个类来进行创建Scene并加载model、camera等，然后运行就会出现这个错误

**Comment by Time-Coder** [comment]
> glass_engine\Screens\QtScreen.py", line 302, in paintGL should_update_scene = scene.generate_meshes() AttributeError: 'method-wrapper' object has no attribute 'generate_meshes'
> 
> 我这边是另外写了一个类来进行创建Scene并加载model、camera等，然后运行就会出现这个错误

请给出一个最小复现代码

**Comment by Hello2015** [comment]
```
from glass_engine import *
from glass_engine.Manipulators import *
from glass_engine.Lights import *

from glass_engine.Geometries import *

from PySide6.QtWidgets import QApplication, QDialog, QHBoxLayout, QVBoxLayout,QMainWindow
from PySide6.QtCore import Qt

def create3DView():
    scene = Scene()

    model = Sphere()

    scene.add(model)

    light = DirLight()
    light.yaw = -45
    light.pitch = -45
    light.generate_shadows = False
    scene.add(light)

    camera_inter = Camera('PySide6', Camera.ProjectionMode.Orthographic)
    camera_inter.screen.manipulator = ModelViewManipulator(distance=5, azimuth=45, elevation=45)
    scene.add(camera_inter)

    hlayout_down = QHBoxLayout()
    hlayout_down.setContentsMargins(0, 0, 0, 0)
    hlayout_down.addWidget(camera_inter.screen)

    vlayout_all = QVBoxLayout()
    vlayout_all.addLayout(hlayout_down)
    return vlayout_all

app = QApplication([])

dialog = QDialog()
dialog.setWindowFlags(Qt.WindowType.WindowMinMaxButtonsHint | Qt.WindowType.WindowCloseButtonHint)
vlayout_all = create3DView()
dialog.setLayout(vlayout_all)
dialog.resize(700, 700)
dialog.show()

app.exec()
```

**Comment by Time-Coder** [comment]
注意看函数 ``create3DView`` 中的局部变量 ``scene`` 对象，在退出函数 ``create3DView`` 后其引用计数变为 0，将被 python 的垃圾回收机制销毁，但在渲染过程中仍会使用 ``scene`` 对象，将导致未定义行为。将 ``scene`` 变为全局变量可防止其引用计数变为 0：
```python
...
scene = None
def create3DView():
    global scene
    scene = Scene()
    # 其他代码
    ...
```
以上代码虽然可以解决问题，但并不是编写 Qt 程序的最佳实践，针对你的代码要实现的功能，正常的 Qt 开发逻辑应该使用如下代码：
```python
class ThreeDViewDialog(QDialog):

    def __init__(self, parent:QWidget=None):
        QDialog.__init__(self, parent=parent)

        self.scene = Scene()  # 保存为成员变量，防止其被销毁
        
        model = Sphere()

        self.scene.add(model)

        light = DirLight()
        light.yaw = -45
        light.pitch = -45
        light.generate_shadows = False
        self.scene.add(light)

        camera_inter = Camera('PySide6', Camera.ProjectionMode.Orthographic)
        camera_inter.screen.manipulator = ModelViewManipulator(distance=5, azimuth=45, elevation=45)
        self.scene.add(camera_inter)

        hlayout_down = QHBoxLayout()
        hlayout_down.setContentsMargins(0, 0, 0, 0)
        hlayout_down.addWidget(camera_inter.screen)

        vlayout_all = QVBoxLayout()
        vlayout_all.addLayout(hlayout_down)
        self.setLayout(vlayout_all)

        self.setWindowFlags(Qt.WindowType.WindowMinMaxButtonsHint | Qt.WindowType.WindowCloseButtonHint)

app = QApplication([])

dialog = ThreeDViewDialog()
dialog.resize(700, 700)
dialog.show()

app.exec()
```

**Comment by Hello2015** [comment]
非常感谢作者的回答，解决了我的燃眉之急

**Comment by Time-Coder** [comment]
非常感谢您使用 Glass Engine，欢迎您发邮件到 binghui.wang@foxmail.com 告诉我你的使用案例，或咨询使用方法，或提bug/新需求，同时也可以获得更及时的回复。

**Comment by caiyingchun** [comment]
> 注意看函数 `create3DView` 中的局部变量 `scene` 对象，在退出函数 `create3DView` 后其引用计数变为 0，将被 python 的垃圾回收机制销毁，但在渲染过程中仍会使用 `scene` 对象，将导致未定义行为。将 `scene` 变为全局变量可防止其引用计数变为 0：
> 
> ```python
> ...
> scene = None
> def create3DView():
>     global scene
>     scene = Scene()
>     # 其他代码
>     ...
> ```
> 
> 以上代码虽然可以解决问题，但并不是编写 Qt 程序的最佳实践，针对你的代码要实现的功能，正常的 Qt 开发逻辑应该使用如下代码：
> 
> ```python
> class ThreeDViewDialog(QDialog):
> 
>     def __init__(self, parent:QWidget=None):
>         QDialog.__init__(self, parent=parent)
> 
>         self.scene = Scene()  # 保存为成员变量，防止其被销毁
>         
>         model = Sphere()
> 
>         self.scene.add(model)
> 
>         light = DirLight()
>         light.yaw = -45
>         light.pitch = -45
>         light.generate_shadows = False
>         self.scene.add(light)
> 
>         camera_inter = Camera('PySide6', Camera.ProjectionMode.Orthographic)
>         camera_inter.screen.manipulator = ModelViewManipulator(distance=5, azimuth=45, elevation=45)
>         self.scene.add(camera_inter)
> 
>         hlayout_down = QHBoxLayout()
>         hlayout_down.setContentsMargins(0, 0, 0, 0)
>         hlayout_down.addWidget(camera_inter.screen)
> 
>         vlayout_all = QVBoxLayout()
>         vlayout_all.addLayout(hlayout_down)
>         self.setLayout(vlayout_all)
> 
>         self.setWindowFlags(Qt.WindowType.WindowMinMaxButtonsHint | Qt.WindowType.WindowCloseButtonHint)
> 
> app = QApplication([])
> 
> dialog = ThreeDViewDialog()
> dialog.resize(700, 700)
> dialog.show()
> 
> app.exec()
> ```

我运行这个例子，出现了这个错误：
```
QPainter::begin: Paint device returned engine == 0, type: 0
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::compositionMode: Painter not active
QPainter::setCompositionMode: Painter not active
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 0
QPainter::setCompositionMode: Painter not active
Traceback (most recent call last):
  File "1.py", line 42, in <module>
    dialog.show()
  File "C:\miniconda3\lib\site-packages\glass_engine\Screens\QtScreen.py", line 302, in paintGL
    should_update_scene = scene.generate_meshes()
AttributeError: 'OpenGL_accelerate.wrapper.CArgCalculator' object has no attribute 'generate_meshes'
```
